# Font - Families
#
# The font families used throughout the site, feel free to rename them to
# the fonts that are used i.e. $Font_Family-Myriad|Minion instead of
# Serif|SansSerif.
#
# Also don't worry about making this a map as you end up with very long lines
# having to do map-get($Font_Families, name) we also tend to have very few so
# a map tends to be overkill.
families:
  sans: 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif
  serif: 'Georgia', 'Times New Roman', serif

# Font - Sizes
#
# Font sizes used across the site, wysiwyg specific sizes are namespaced with
# wys- to make it clear these are the sizings that are choosable in the
# wysiwyg. For sizes just used on the site use a non namespaced name
#
# !!! Make sure the keys match the keys in the equivalent line-height map
sizes:
  wysiwyg:
    base:
      lg: 20px
      md: 18px
      sm: 16px

    md:
      lg: 24px
      md: 20px
      sm: 18px

  base:
    xlg: 24px
    lg: 22px
    md: 20px
    sm: 18px
    xsm: 16px
    normal: 16px
    root: 16px

  md:
    xlg: 32px
    lg: 28px
    md: 20px
    sm: 18px
    xsm: 18px
    normal: 16px
    root: 16px

# Line heights
#
# The line heights that get paired with our previously set font-sizes. Again
# namespace them with Wysiwyg & Site for ease of use
#
# !!! Make sure the keys match the keys in the equivalent font-size map
lineHeights:
  wysiwyg:
    base:
      lg: 30px
      md: 28px
      sm: 26px

    md:
      lg: 34px
      md: 30px
      sm: 28px

  base:
    xlg: 34px
    lg: 32px
    md: 30px
    sm: 28px
    xsm: 26px
    normal: 26px
    root: 26px

  md:
    xlg: 42px
    lg: 38px
    md: 30px
    sm: 28px
    xsm: 28px
    normal: 26px
    root: 26px

